version: "3"

services:
  web:
    container_name: "snack_bar_app"
    build: .
    ports:
      - "80:80"
      - "8080:8080"
      - "5173:5173"
      - "3000:3000"
    volumes:
      - .:/var/www/html
    tty: true
    stdin_open: true